### ISSUE TITLE
Getting chromium on windows fails

### ISSUE THREAD

**Issue by johnroper100** [szeged/sprocket#5]
I checked out the sources fine, and then when I went to do the next step I got this error:

```C:\Users\johnr\Documents>cd sprocket

C:\Users\johnr\Documents\sprocket>python tools/checkout_chromium.py --x86_64
Traceback (most recent call last):
  File "tools/checkout_chromium.py", line 25, in <module>
  File "C:\Python27\lib\subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

C:\Users\johnr\Documents\sprocket>

**Comment by dati91** [comment]
Sorry, but the supported platforms are Linux and Android.

**Comment by johnroper100** [comment]
ok
